# Generated by Django 2.1.3 on 2019-12-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_earned', models.CharField(max_length=50)),
                ('amount_earned', models.FloatField()),
                ('date_earned', models.DateField()),
                ('message_earned', models.TextField()),
            ],
        ),
    ]
