# Generated by Django 2.1.3 on 2019-12-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_income_username_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_expense', models.CharField(max_length=50)),
                ('what_expense', models.CharField(max_length=50)),
                ('amount_expense', models.FloatField()),
                ('date_expense', models.DateField()),
                ('message_expense', models.TextField()),
            ],
        ),
    ]
